---
- name: Deploy Citrix CVAD Servers
  hosts: localhost
  gather_facts: no
  connection: local
  vars_prompt:
    - name: "XenServer_IP_var"
      prompt: "Enter XenServer IP Address"
      private: no
      default: "10.20.8.10"
    - name: "XenServer_user_var"
      prompt: "Enter XenServer username"
      private: no
      default: "root"
    - name: "XenServer_pass_var"
      prompt: "Enter XenServer password"
      private: yes
      default: "p@ssw0rd"
  vars_files:
    - pd_cvad_vars.yml
  tasks:
    - name: Create VM
      xenserver_guest:
        hostname: "{{ XenServer_IP_var }}"
        username: "{{ XenServer_user_var }}"
        password: "{{ XenServer_pass_var }}"
        state: poweredon
        #state: present
        template: "{{ template }}"
        linked_clone: yes
        name_desc: "{{ item.name }}"
        name: "{{ item.name }}"
        disks:
        - size_gb: "{{ system_zise }}"
          name: "{{ item.name }}_System"
          sr: "{{ system_storage }}"
        - size_gb: "{{ data_zise }}"
          name: "{{ item.name }}_Data"
          sr: "{{ data_storage }}"
        hardware:
          num_cpus: "{{ vm_vcpu }}"
          num_cpu_cores_per_socket: "2"
          memory_mb: "{{ vm_memory }}"
        networks:
        - name: "{{ vm_network }}"
          type: "static"
          ip: "{{ item.ip }}"
          netmask: "{{ vm_netmask }}"
          gateway: "{{ vm_gateway }}"
      loop: "{{ vms }}"







